codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 82%
        threshold: 1%
        if_ci_failed: error
    
    patch:
      default:
        target: 82%
        threshold: 1%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
